package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.Privilige;
import com.briup.apps.cms.bean.PriviligeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PriviligeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	long countByExample(PriviligeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int deleteByExample(PriviligeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int insert(Privilige record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int insertSelective(Privilige record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	List<Privilige> selectByExample(PriviligeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	Privilige selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Privilige record, @Param("example") PriviligeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int updateByExample(@Param("record") Privilige record, @Param("example") PriviligeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int updateByPrimaryKeySelective(Privilige record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table base_privilege
	 *
	 * @mbg.generated Tue Nov 12 20:20:47 CST 2019
	 */
	int updateByPrimaryKey(Privilige record);
}